<?php
declare(strict_types=1);

namespace OCA\EgoNextApp\Preview;

use OCP\Files\File;
use OCP\Files\FileInfo;
use OCP\IConfig;
use OCP\IImage;
use OCP\Image;
use OCP\Preview\IProviderV2;
use Psr\Log\LoggerInterface;

/**
 * Preview provider that consumes the PNG previews generated by the egonextapp
 * background jobs instead of relying on Imagick.
 */
class HeicPreviewProvider implements IProviderV2 {
    public const MIMETYPE_REGEX = '/image\/(x-)?hei(f|c)/';

    private ?string $dataDirectory = null;
    private ?string $instanceId = null;

    public function __construct(
        private IConfig $config,
        private LoggerInterface $logger,
    ) {
    }

    public function getMimeType(): string {
        return self::MIMETYPE_REGEX;
    }

    public function isAvailable(FileInfo $file): bool {
        if (!$this->supportsMime($file->getMimeType())) {
            return false;
        }

        return $this->selectPreviewPath($file->getId(), 32) !== null;
    }

    public function getThumbnail(File $file, int $maxX, int $maxY): ?IImage {
        if (!$this->supportsMime($file->getMimeType())) {
            return null;
        }

        $target = max($maxX, $maxY);
        $previewPath = $this->selectPreviewPath($file->getId(), $target);
        if ($previewPath === null) {
            $this->logger->debug('[egonextapp] Anteprima HEIC mancante', [
                'file' => $file->getPath(),
                'target' => $target,
            ]);
            return null;
        }

        $image = new Image();
        if (!$image->loadFromFile($previewPath) || !$image->valid()) {
            $this->logger->warning('[egonextapp] Anteprima HEIC non valida', [
                'file' => $file->getPath(),
                'preview' => $previewPath,
            ]);
            return null;
        }

        $image->scaleDownToFit($maxX, $maxY);
        return $image;
    }

    private function supportsMime(?string $mimeType): bool {
        if ($mimeType === null) {
            return false;
        }
        return (bool)preg_match(self::MIMETYPE_REGEX, $mimeType);
    }

    private function selectPreviewPath(?int $fileId, int $target): ?string {
        $dir = $this->buildPreviewDirectory($fileId);
        if ($dir === null) {
            return null;
        }

        $previews = $this->listAvailablePreviews($dir);
        if ($previews === []) {
            return null;
        }

        foreach ($previews as $preview) {
            if ($preview['size'] >= $target) {
                return $preview['path'];
            }
        }

        $last = $previews[count($previews) - 1];
        return $last['path'];
    }

    /**
     * @return array<int, array{size:int, path:string}>
     */
    private function listAvailablePreviews(string $dir): array {
        if (!is_dir($dir)) {
            return [];
        }

        $files = glob($dir.'/*.png');
        if ($files === false) {
            return [];
        }

        $previews = [];
        foreach ($files as $filePath) {
            $basename = basename($filePath);
            if (!preg_match('/^(\d+)-(\d+)\.png$/', $basename, $matches)) {
                continue;
            }
            $previews[] = [
                'size' => (int)$matches[1],
                'path' => $filePath,
            ];
        }

        usort($previews, static fn(array $a, array $b) => $a['size'] <=> $b['size']);
        return $previews;
    }

    private function buildPreviewDirectory(?int $fileId): ?string {
        if ($fileId === null) {
            return null;
        }

        $instanceId = $this->getInstanceId();
        if ($instanceId === '') {
            return null;
        }

        return $this->getDataDirectory().'/appdata_'.$instanceId.'/preview/'.$fileId;
    }

    private function getDataDirectory(): string {
        if ($this->dataDirectory === null) {
            $this->dataDirectory = rtrim(
                (string)$this->config->getSystemValue('datadirectory', \OC::$SERVERROOT.'/data'),
                '/'
            );
        }
        return $this->dataDirectory;
    }

    private function getInstanceId(): string {
        if ($this->instanceId === null) {
            $this->instanceId = (string)$this->config->getSystemValue('instanceid', '');
            if ($this->instanceId === '') {
                $this->logger->warning('[egonextapp] Instance ID mancante: impossibile risolvere il path preview HEIC');
            }
        }
        return $this->instanceId;
    }
}
